In [1]:
import os
os.getcwd()

'/root'

In [2]:
# !unzip /root/autodl-tmp/Match_Data.zip -d /root/autodl-tmp/

In [3]:
import gc

In [4]:
import pickle
import os
Name = ['MeltedToast', 'Mithraaaa']
feat = []
army = []
Y = []
id = []
for name in Name:
    file_path = '/root/autodl-tmp/Match_Data/'+name
    replays = os.listdir(file_path)
    for item in replays:
        replay_path = file_path + '/' + item
        with open(replay_path,"rb") as file:
            total = pickle.load(file)
            feat.append(total["features"])
            army.append(total["armies"])
            Y.append(total["kings"])
            id.append(total["id"])

# print(len(X))
# print(data[0])

In [5]:
print(len(Y))

4375


In [6]:
mx = 0
feat_new = []
army_new = []
Y_new = []
for item in range(0,len(Y)):
    mx = max(mx, len(Y[item]))
    if (len(Y[item])<=1000):
        feat_new.append(feat[item])
        army_new.append(army[item])
        Y_new.append(Y[item])
        # print(id[item])
print(mx)
del feat, army, Y, id
gc.collect()

1414


0

In [7]:
feat = feat_new
army = army_new
Y = Y_new

In [8]:
del feat_new, army_new, Y_new
gc.collect()

0

In [9]:
import numpy as np
print(len(feat))
def transform_to_numpy(X):
    res = []
    for item in X:
        XX = []
        flag=0
        for item2 in item:
            try:
                # print(item2)
                # print("TRY1: ",get_list_depth(item2),len(item2),)
                XX.append(np.array(item2))
            except ValueError as e:
                print(item2)
                # print("TRY2: ",get_list_depth(item2),len(item2))
                flag=1
                break
        if flag:
            break
        res.append(np.array(XX))
    return res

feat_np = transform_to_numpy(feat)
army_np = transform_to_numpy(army)
Y_np = []
for item in Y:
    Y_np.append(np.array(item))
# print(Y_np[0])

4359


In [10]:
del feat
del army
del Y
gc.collect()

0

In [16]:
from tensorflow.keras.preprocessing.sequence import pad_sequences

for i, (feat_seq, army_seq, y_seq) in enumerate(zip(feat_np, army_np, Y_np)):
    target_shape = (1000, 25, 25)
    padding_needed = target_shape[0] - feat_seq.shape[0]
    feat_padded = np.pad(feat_seq, ((0, padding_needed), (0, 0), (0, 0)), mode='constant', constant_values=-1)
    # print(feat_padded)
    
    army_padded = np.pad(army_seq, ((0, padding_needed), (0, 0), (0, 0)), mode='constant', constant_values=-1)
    # print(army_padded)
    # print(feat_padded.shape, army_padded.shape)
    target_shape = (1000, 2)
    padding_needed = target_shape[0] - y_seq.shape[0]
    Y_padded = np.pad(y_seq, ((0, padding_needed), (0, 0)), mode='constant', constant_values=-1)
    result = Y_padded[:, 0] * 25 + Y_padded[:, 1]
    
    grid_values = np.arange(625).reshape(25, 25)
    id = np.tile(grid_values, (1000, 1, 1))
    if i==0:
        print(id)
        print(result)
    # print(Y_padded.shape)
    np.savez(f'/root/autodl-tmp/Numpy_Data/data_row_{i}.npz', id=id, feat_padded=feat_padded, army_padded=army_padded, Y_padded=result)

[[[  0   1   2 ...  22  23  24]
  [ 25  26  27 ...  47  48  49]
  [ 50  51  52 ...  72  73  74]
  ...
  [550 551 552 ... 572 573 574]
  [575 576 577 ... 597 598 599]
  [600 601 602 ... 622 623 624]]

 [[  0   1   2 ...  22  23  24]
  [ 25  26  27 ...  47  48  49]
  [ 50  51  52 ...  72  73  74]
  ...
  [550 551 552 ... 572 573 574]
  [575 576 577 ... 597 598 599]
  [600 601 602 ... 622 623 624]]

 [[  0   1   2 ...  22  23  24]
  [ 25  26  27 ...  47  48  49]
  [ 50  51  52 ...  72  73  74]
  ...
  [550 551 552 ... 572 573 574]
  [575 576 577 ... 597 598 599]
  [600 601 602 ... 622 623 624]]

 ...

 [[  0   1   2 ...  22  23  24]
  [ 25  26  27 ...  47  48  49]
  [ 50  51  52 ...  72  73  74]
  ...
  [550 551 552 ... 572 573 574]
  [575 576 577 ... 597 598 599]
  [600 601 602 ... 622 623 624]]

 [[  0   1   2 ...  22  23  24]
  [ 25  26  27 ...  47  48  49]
  [ 50  51  52 ...  72  73  74]
  ...
  [550 551 552 ... 572 573 574]
  [575 576 577 ... 597 598 599]
  [600 601 602 ... 622 623 6

OSError: [Errno 28] No space left on device

In [ ]:
import shutil
shutil.make_archive('Numpy_Data', 'zip', '/root/autodl-tmp/Numpy_Data')

In [ ]:
# del feat_np,army_np,Y_np
# gc.collect()

In [ ]:
print(feat_padded.shape)
print(army_padded.shape)
print(Y_padded.shape)